version: '3.8'

services:
  pricex:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pricex
    volumes:
      - ./config.test.json:/app/config.json
    command:
      - '--web.listen-address=0.0.0.0:9169'
    ports:
      - 9169:9169

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_mem
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090